spring.application.name=backend
spring.mongodb.uri=${MONGO_DB_URI}
tmdb.settings.token=${TMDB_READ_TOKEN}
tmdb.settings.language=de-DE
tmdb.settings.include_adult=false
spring.security.oauth2.client.registration.github.client-id=${GITHUB_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_SECRET}
spring.security.oauth2.client.registration.github.scope=none
app.url=${APP_URL}
