spring.application.name=backend
spring.mongodb.uri=${MONGO_DB_URI}
tmdb.settings.token=${TMDB_READ_TOKEN}
tmdb.settings.key=${TMDB_API_KEY}
tmdb.settings.language=de-DE
tmdb.settings.include_adult=false
